### ISSUE TITLE
navViewModel not persisted

### ISSUE THREAD

**Issue by danielbuechele** [matteopuc/swiftui-navigation-stack#33]
This might be due to my limited knowledge of SwiftUI or a flaw in my app. However, it happens that `NavigationStackView` is re-initialized for rerendering and because `navViewModel` is created in the constructor, it forgets its state.

Marking it is a `@StateObject` fixes the problem for me, but this method is only available starting iOS 14, so I'm not sure if that's what you want for this library.

And as I mentioned, perhaps `NavigationStackView` shouldn't be reinitialized at all, but that seems to be a problem with either SwiftUI or my app.

**Comment by danielbuechele** [comment]
What also solves the problem for me is to wrap `NavigationStackView` in its own component:

```
public struct Navigation<Content: View>: View {
    let content: Content

    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }
    
    public var body: some View {
        NavigationStackView {
            content
        }
    }
}
```

**Comment by matteopuc** [comment]
Hi @danielbuechele, sorry for the late response. In order for me to help you understanding why the `NavigationStackView` gets recreated I'd need to take a look at your code (at least a part of your code that can reproduce the issue). Just a question: where do you create your `NavigationStackView`? Usually you want to create it as the very first view of your app.
