### ISSUE TITLE
How to manually make view .root

### ISSUE THREAD

**Issue by ch05en** [matteopuc/swiftui-navigation-stack#46]
I have this app where I use userDefaults to store if the user was previously logged in. If they weren't previousy logged in, the first view is a login page. If they were previously logged in, the first view is a different view. That said, I want to implement a logout feature. But if they were already logged in, and the first view is not the login page, how can I pop back to a view that never appeared ie (the login page).

**Comment by mustafaozhan** [comment]
This is how I deal with similar scenario
https://github.com/CurrencyConverterCalculator/CCC/blob/master/ios/CCC/UI/MainView.swift#L27

**Comment by matteopuc** [comment]
Hi @ch05en I think something like this might work for you (you can copy paste the example here below and try it yourself):

```
@main
struct NavigationStackExampleApp: App {
    var body: some Scene {
        WindowGroup {
            NavigationStackView {
                DispatcherView()
            }
        }
    }
}

struct DispatcherView: View {
    @AppStorage("isLoggedIn") var isLoggedIn = false

    var body: some View {
        if isLoggedIn {
            Homepage()
        } else {
            LoginView()
        }
    }
}

struct LoginView: View {
    @EnvironmentObject private var navStack: NavigationStack
    @AppStorage("isLoggedIn") var isLoggedIn = false

    var body: some View {
        VStack {
            Text("LOGIN PAGE")
            Button("Tap to login") {
                isLoggedIn = true
                navStack.push(Homepage())
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct Homepage: View {
    @EnvironmentObject private var navStack: NavigationStack

    var body: some View {
        VStack {
            Text("HOMEPAGE")
            Button("Go to logout page") {
                navStack.push(LogoutView())
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct LogoutView: View {
    @EnvironmentObject private var navStack: NavigationStack
    @AppStorage("isLoggedIn") var isLoggedIn = false

    var body: some View {
        VStack {
            Text("LOGOUT PAGE")
            Button("Tap to logout") {
                isLoggedIn = false
                navStack.pop(to: .root)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}
```

Run this example and tap on login. Then kill the app and run it again. This time the homepage will immediately show up. Now, if you tap on logout you'll see the login page appearing on pop.
Please, note that I've used `AppStorage` just as a convenience way to access `UserDefaults`, but it's not mandatory.

**Comment by ch05en** [comment]
Hey @matteopuc. IT WORKED!!. Really appreciate the time you took to help me out here. Thank You.
