### ISSUE TITLE
@ObservedObject var viewModel: ViewModel

### ISSUE THREAD

**Issue by par400** [matteopuc/swiftui-navigation-stack#59]
you have mentioned programmatic push/pop in the examples, but it's not clear how you implemented the `ObservedObject var viewModel: ViewModel`, and what it's purpose is, and what function `performBackgroundActivities()` is doing, would it be same if you just called ` DispatchQueue.main.async {
                    self.navigationStack.push(ChildView())
                }` inside button's action?, can you explain this more? or do we have to implement `ViewModel` logic ourselves

```swift
struct MyHome: View {
    @ObservedObject var viewModel: ViewModel
    @EnvironmentObject private var navigationStack: NavigationStack

    var body: some View {
        Button(action: {
            self.viewModel.performBackgroundActivities(withCallback: {
                DispatchQueue.main.async {
                    self.navigationStack.push(ChildView())
                }
            })
        }, label: {
            Text("START BG ACTIVITY")
        })
    }
}
```

**Comment by matteopuc** [comment]
> you have mentioned programmatic push/pop in the examples, but it's not clear how you implemented the `ObservedObject var viewModel: ViewModel`, and what it's purpose is, and what function `performBackgroundActivities()` is doing, would it be same if you just called ` DispatchQueue.main.async { self.navigationStack.push(ChildView()) }` inside button's action?, can you explain this more? or do we have to implement `ViewModel` logic ourselves
> 
> ```
> `struct MyHome: View {
>     @ObservedObject var viewModel: ViewModel
>     @EnvironmentObject private var navigationStack: NavigationStack
> 
>     var body: some View {
>         Button(action: {
>             self.viewModel.performBackgroundActivities(withCallback: {
>                 DispatchQueue.main.async {
>                     self.navigationStack.push(ChildView())
>                 }
>             })
>         }, label: {
>             Text("START BG ACTIVITY")
>         })
>     }
> }`
> ```

Hi @par400 in the README you can find a silly example about programmatic push. What I called `viewModel` in that example is just an object (relying on the MVVM pattern, as stated by @nosenergies) that contains some logic (for example the `performBackgroundActivities `, which is just an example). What is important is that you can programmatically push and pop by directly accessing the navigation stack environment object. In other words, you can rewrite the example this way:

```swift
struct MyHome: View {
    @EnvironmentObject private var navigationStack: NavigationStack

    var body: some View {
        Button(action: {
            self.navigationStack.push(ChildView())
        }, label: {
            Text("START BG ACTIVITY")
        })
    }
}
```

And it will work as expected.
