### ISSUE TITLE
Question: how to check if view with ID is already in stack?

### ISSUE THREAD

**Issue by sdelaysam** [matteopuc/swiftui-navigation-stack#64]
Hi there!
I want to implement such scenario: "Check if view is in stack, if yes, pop to existing entry, otherwise push the new one"?
As far as I can see from the source code, it's currently not possible.
Am I missing something?

**Comment by matteopuc** [comment]
Hi @sdelaysam I've just added this useful feature here https://github.com/matteopuc/swiftui-navigation-stack/commit/042e865e8d2b509ce714eacd6bd5ec4acf1f3116 I'll update the README and release a new version soon. In the meantime, if you are using the navigation stack as a Swift Package you can make it point develop, which is the branch where the feature currently is. Thanks.
