### ISSUE TITLE
Support for Xcode 14 and new SwiftUI API

### ISSUE THREAD

**Issue by domfz** [matteopuc/swiftui-navigation-stack#75]
Since SwiftUI added a NavigationStack to their API, the projects won't build due to same naming with the new Xcode 14 beta. 
Any possible solutions?

**Comment by domfz** [comment]
I wrote a `typealias` in a new File where only Foundation and NavigationStack are imported and replaced all my usages with the typealias, this works as a workaround.

**Comment by Sadmansamee** [comment]
can share? @domfz

**Comment by domfz** [comment]
> can share? @domfz

```
import Foundation
import NavigationStack

// Workaround: This fixes usage of NavigationStack Library with Xcode 14
typealias NavigationStackCompat = NavigationStack

```

**Comment by Sadmansamee** [comment]
I will rather fork it and change

**Comment by Sadmansamee** [comment]
#77

**Comment by Sadmansamee** [comment]
@matteopuc @domfz this should be closed now
