### ISSUE TITLE
iOS 16 transitions malfunctioning

### ISSUE THREAD

**Issue by enricgd** [matteopuc/swiftui-navigation-stack#80]
Hi there,
After updating a device to iOS 16 the navigation is presenting some strange malfunctioning sometimes:
Here is a View being pushed in the old version, entering from the right and "pushing" the old one to the left:
![old](https://user-images.githubusercontent.com/40291127/189860074-a68b7c29-a4c7-43ed-8de6-8e5e0056c6ab.png)

Here is same views with iOS 16 (never happened before). Now the old view starts to go to the right leaving a black space behind, at the same time that the new one is coming also from the right, making a strange animation:
![new](https://user-images.githubusercontent.com/40291127/189860309-1cacaec6-c8a6-429a-891e-bf82b8b201a3.png)

It also happens (but the other way around) when poping views.

Thanks a lot!!

**Comment by mustafaozhan** [comment]
+1

**Comment by CureleaAndrei** [comment]
Hi, I am facing the same issue (on iOS 16 only). For what I can tell and tested it seems that the popped view animation is broken (it slides to right instead of left). Have you found a solution for this ?

**Comment by mustafaozhan** [comment]
I make my all animations `opacity` temporary as a workaround, but couldn't find a `real` solution yet

**Comment by toobiz** [comment]
Setting transitionType to .none at least turns off the faulty animation. I tried to figure out what went wrong in the code but not no luck. 

`NavigationStackView(transitionType: .none)`

**Comment by samjoly** [comment]
I test this simple script, and it has the same issue with iOS16:
https://stackoverflow.com/questions/63782469/swiftui-how-to-have-next-and-back-animations/63782921#63782921

This thread might help:
Has the behavior of asymmetric transitions changed in SwiftUI 4 / iOS 16?
https://developer.apple.com/forums/thread/714977

**Comment by samjoly** [comment]
Hi team,
I think I found a fix on NavigationStackCompat.swift.

1) Line 27, I use @Published on navigationType
` @Published private(set) var navigationType = NavigationType.push`

2) Line 61, I set navigationType before the animation
  ` navigationType = .push`
      `  withAnimation(easing) {`
      
3) Line 71, I set navigationType before the animation
`  navigationType = .pop`
      `  withAnimation(easing) {`

Let me know what you think. 
Thanks

**Comment by toobiz** [comment]
@samjoly Your fix works for me. Will you create a pull request?

**Comment by mustafaozhan** [comment]
Hey hello @matteopuc & @samjoly,

Since no-one had encouraged to create the PR, I just created it from @samjoly comment. Please check if everything is fine and let's merge it in order to have it in the library 🙂

**Comment by matteopuc** [comment]
Thank you so much for your help guys, the bug is fixed! 🙏
