### ISSUE TITLE
Xcode 14 Compiling Issue

### ISSUE THREAD

**Issue by BerkinSi** [matteopuc/swiftui-navigation-stack#82]
Hello, after updating to Xcode 14, I am not able to run my project because name NavigationStack conflicts with one of the new SwiftUI Native classes.

Has anyone else ran into this issue? If so, were you able to find a solution?

**Comment by matteopuc** [comment]
Hi @BerkinSi if you are using SPM the problem is fixed (with the version 1.0.5). The Pod has not been updated to that version, though.

**Comment by BerkinSi** [comment]
Thank you will give it a try

**Comment by BerkinSi** [comment]
oh so I should also update my imports too. Thank you for the tip

**Comment by matteopuc** [comment]
The import is the same, it's just the `NavigationStack` class that changes its name to `NavigationStackCompat`.

**Comment by BerkinSi** [comment]
Got it thanks!
